### DISCUSSION TITLE
Не можу завантажити мовний пакет за допомогою Home Assistant

### DISCUSSION THREAD

**Discussion by sverdlyuk** [oleksandr-belei/dreame-vacuum-uk-voice-packs#2] [General]
Дякую за надзвичайну роботу! Наскільки бачу файл називається uk_female_pensive, але для пилососів Dreame це має бути архів tar.gz, тобто має бути uk_female_pensive.tar.gz Якщо підставляти просто URL файлу, то нічого не відбувається. Я зміг завантажити файл, змінив його назву на uk_female_pensive.tar.gz і тоді він розпакувався. Пропоную змінити назву файлу uk_female_pensive на uk_female_pensive.tar.gz та завантажити повторно в цей репо. Дякую!

Зараз команда виглядає так:
```
service: dreame_vacuum.vacuum_install_voice_pack
data:
  lang_id: UA
  url: >-
    https://github.com/oleksandr-belei/dreame-vacuum-uk-voice-packs/blob/main/voice_packs/uk_female_pensive
  md5: 55bfe4272ce1e77d9bbafebf9ec99330
  size: 3585448
target:
  entity_id: vacuum.mops

```

Має бути так:
```
service: dreame_vacuum.vacuum_install_voice_pack
data:
  lang_id: UA
  url: >-
    https://github.com/oleksandr-belei/dreame-vacuum-uk-voice-packs/blob/main/voice_packs/uk_female_pensive.tar.gz
  md5: new md5sum
  size: new size
target:
  entity_id: vacuum.mops

```
